#!/bin/bash

USDPLUGINEXAMPLES_INSTALL_ROOT=/apps/USDSandbox

appendEnv PXR_PLUGINPATH_NAME ${USDPLUGINEXAMPLES_INSTALL_ROOT}/lib/usd
appendEnv PXR_PLUGINPATH_NAME ${USDPLUGINEXAMPLES_INSTALL_ROOT}/plugin/usd
appendEnv PYTHONPATH ${USDPLUGINEXAMPLES_INSTALL_ROOT}/lib/python
appendEnv LD_LIBRARY_PATH ${USDPLUGINEXAMPLES_INSTALL_ROOT}/lib
